executable            = batch_limits_toys.sh
transfer_input_files = $(filename)
arguments             = $(Step) $(filename)
output                = output/$(ClusterId).$(ProcId).out
error                 = error/$(ClusterId).$(ProcId).err
log                   = log/$(ClusterId).log
+JobFlavour           = "workday"
+AccountingGroup = "group_u_CMST3.all"
# RequestCpus           = 8
queue 6 filename matching datacard_ged_hinvmass_axion*.txt
